services:
  # --- Reverse Proxy---
  proxy:
    image: nginx:alpine
    container_name: showcase-acc-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - showcase-webapp
    networks:
      - showcase-network
    restart: unless-stopped

  # --- Backend API ---
  showcase-api:
    image: ${API_IMAGE:-ghcr.io/OWNER/showcase-api:latest}
    container_name: showcase-acc-api
    networks:
      - showcase-network
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.acceptance
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    restart: unless-stopped

  # --- Frontend Web App ---
  showcase-webapp:
    image: ${WEBAPP_IMAGE:-ghcr.io/OWNER/showcase-webapp:latest}
    container_name: showcase-acc-webapp
    environment:
      - NEXT_PUBLIC_API_URL=/api
    networks:
      - showcase-network
    depends_on:
      - showcase-api
    restart: unless-stopped

  # --- Postgress DB ---
  db:
    image: postgres:18.1-alpine3.22
    container_name: showcase-acc-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - showcase-network
    volumes:
      - postgres_data_acceptance:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  showcase-network:
    driver: bridge

volumes:
  postgres_data_acceptance:
